version: "3.7"
services:
  postgredb:
    build:
      context: ../
      dockerfile: ./containers/db/Dockerfile
    restart: always
    env_file:
      - ../conf/db/db.env
    volumes:
      - /data/itp-db:/var/lib/postgresql/data
    networks:
      - itp
  apiserver:
    build:
      context: ../
      dockerfile: ./containers/apiserver/Dockerfile
    restart: always
    depends_on:
      - postgredb
    ports:
      - "8088:8088"
    volumes:
      - ../conf/apiserver/app.conf:/go/bin/app.conf:z
    networks:
      - itp
  proxy:
    image: nginx:1.12.1-alpine
    depends_on: 
      - apiserver
    restart: always
    ports:
      - "8089:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:z
      - ../src/ui/dist:/usr/share/nginx/html:z
    networks:
      - itp
configs:
  init-db:
    file: ./containers/db/init-db.sh
networks:
  itp:
